# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release_1.13.0

on:
  push:
    branches: [ release/1.13.0 ]
  pull_request:
    branches: [ release/1.13.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: chmod +x ./install-dependencies.sh && ./install-dependencies.sh
    - name: Build with Maven
      run: mvn -B package --file pom.xml
